version: '3.3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/DB_PASS
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_USER: morac
    volumes:
     - db:/var/lib/mysql
    networks:
     - mariadb
    secrets:
     -
      source: wordpress_db-pass
      target: db-pass
    logging:
      driver: json-file
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
         - node.role == manager
  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/DB_PASS
    volumes:
     - wordpress:/var/www/html
    networks:
     - traefik-public
     - mariadb
    secrets:
     -
      source: wordpress_db-pass
      target: db-pass
    logging:
      driver: json-file
    deploy:
      labels:
        - traefik.enable=true
        - traefik.constraint-label=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.http.routers.${STACK_NAME?variable not set}-http.rule=Host(`${DOMAIN?variable not set}`)
        - traefik.http.routers.${STACK_NAME?variable not set}-http.entrypoints=http
        - traefik.http.routers.${STACK_NAME?variable not set}-http.middlewares=https-redirect
        - traefik.http.routers.${STACK_NAME?variable not set}-https.entrypoints=https
        - traefik.http.routers.${STACK_NAME?variable not set}-https.rule=Host(`${DOMAIN?variable not set}`)
        - traefik.http.routers.${STACK_NAME?variable not set}-https.tls=true
        - traefik.http.routers.${STACK_NAME?variable not set}-https.tls.certresolver=le
        - traefik.http.services.${STACK_NAME?variable not set}.loadbalancer.server.port=80

      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
networks:
  mariadb:
    driver: overlay
  traefik-public:
    external: true
volumes:
  db:
    driver: local
  wordpress:
    driver: local
secrets:
  DB_PASS:
    file: ./.secrets/DB_PASS.secret
